# Generated by Django 4.2.1 on 2025-01-05 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_withdrawal_transfer_deposit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banks',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='remarks',
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='tax_deduction',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='banks',
            name='name',
            field=models.CharField(default='bank', max_length=50),
        ),
        migrations.AlterField(
            model_name='banks',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bank', to=settings.AUTH_USER_MODEL),
        ),
    ]
